[pytest]
testpaths = test
python_files = *test*.py
python_classes = *Test*
python_functions = *test*
markers =
    ui: тесты пользовательского интерфейса (UI‑тесты)
    api: тесты на бизнес‑логику через прямые вызовы API (API‑тесты)